<?php
/**
* @copyright	Copyright (C) 2012 - JoomSpirit. All rights reserved.
*/
defined('_JEXEC') or die('Restricted access');
if(isset($_REQUEST["finish"])){
	if($_REQUEST["finish"] == "true") {
?>
<html>
<head>
<script src="/includes/jquery-1.11.1.js" type="text/javascript"></script>
<?php
		if($_REQUEST['return_param'] != null && $_REQUEST['return_param'] != ""){
?>
<script src="/includes/ThaiPattara_Function.js" type="text/javascript"></script>
<?php
		}
?>
</head>
<body>
<?php 
if(strpos($_REQUEST['return_param'], 'lang#ru') === FALSE) {
?>
пожалуйста, подождите ...<br />
<?php
} else {
?>
Please Wait ...<br />
<?php
}
?>
<script>
<?php 
		if($_REQUEST['return_param'] != null && $_REQUEST['return_param'] != ""){
			$return_param = array();
			$myParam = explode('!', $_REQUEST['return_param']);
			foreach($myParam as $the_param){
				$tmp = explode('#', $the_param);
				$return_param[$tmp[0]] = $tmp[1];
			}
			//print_r($return_param);
/*
payer_first_name			Customer's first name
payer_last_name				Customer's last name
payer_email					Customer's primary email address. Use this email to provide any credits.
payer_address_street		Customer's street address.
payer_address_city			City of customer's address
payer_address_state			State of customer's address
payer_address_country		Country of customer's address
payer_address_zip			Zip code of customer's address.
payer_address_status		Whether the customer provided a confirmed address.

item_name1					Item name as passed by you
mc_gross					Full amount of the customer's payment
mc_currency					this is the currency of the payment.

payment_date				Time/Date stamp generated by PayPal, in the following format: HH:MM:SS Mmm DD, YYYY PDT
payment_status				The status of the payment:
payment_type				Payment type.
txn_id						Paypal transaction id.
*/
?>
var doneMsg = "DONE !!\r\nIF YOU HAD ANY QUESTION. PLEASE DON'T HESITATE TO CONTACT US !!";
var post_data = {
	'blank_page'		: true,
<?php
if($return_param["card"] == "giftcer"){
?>
	'spa_program'   	: "<?php echo $return_param["spa_program"];?>", 
	'money_amount'  	: "<?php echo $return_param["money_amount"];?>", 
	'sender_name'		: "<?php echo $return_param["sender_name"];?>",
	'sender_email'		: "<?php echo $return_param["sender_email"];?>",
	'sender_phone'		: "<?php echo $return_param["sender_phone"];?>",
	'recipient_name'	: "<?php echo $return_param["recipient_name"];?>",
	'recipient_email'	: "<?php echo $return_param["recipient_email"];?>",
	'subject'			: "<?php echo $return_param["subject"];?>",
	'message'			: "<?php echo $return_param["message"];?>",
	'mail_subject'		: "NEW E-GIFT CERTIFICATE ORDER",
<?php
}
?>
<?php
if($return_param["card"] == "membercard"){
?>
	'customer_name'		: "<?php echo $return_param["customer_name"];?>",
	'customer_email'	: "<?php echo $return_param["customer_email"];?>",
	'customer_phone'	: "<?php echo $return_param["customer_phone"];?>",
	'mail_subject'		: "NEW MEMBER CARD ORDER",
<?php
}
?>
	'lang'				: "<?php echo $return_param["lang"];?>",
	'card_type'  		: "<?php echo $return_param["card_type"];?>", 
	'original_price'    : "<?php echo $return_param["original_price"];?>", 
	'price'     		: "<?php echo $return_param["price"];?>", 
	'currency'         	: "<?php echo $return_param["currency"];?>",
	'currency_text'		: "<?php echo $return_param["currency_text"];?>",
	
	'payer_first_name'	: "<?php echo $_POST["first_name"];?>",
	'payer_last_name' : "<?php echo $_POST["last_name"];?>",
	'payer_email' : "<?php echo $_POST["payer_email"];?>",
	'payer_address_street' : "<?php echo $_POST["address_street"];?>",
	'payer_address_city' : "<?php echo $_POST["address_city"];?>",
	'payer_address_state' : "<?php echo $_POST["address_state"];?>",
	'payer_address_country' : "<?php echo $_POST["address_country"];?>",
	'payer_address_zip' : "<?php echo $_POST["address_zip"];?>",
	'payer_address_status' : "<?php echo $_POST["address_status"];?>",
	'item_name1' : "<?php echo $_POST["item_name1"];?>",
	'mc_gross' : "<?php echo $_POST["mc_gross"];?>",
	'mc_currency' : "<?php echo $_POST["mc_currency"];?>",
	'payment_date' : "<?php echo $_POST["payment_date"];?>",
	'payment_status' : "<?php echo $_POST["payment_status"];?>",
	'payment_type' : "<?php echo $_POST["payment_type"];?>",
	'transaction-id'	: "<?php echo $_POST["txn_id"];?>"
};
<?php
if($return_param["card"] == "giftcer") { 
?>
post(post_data, "http://<?php echo $_SERVER['SERVER_NAME'];?>/submitGiftCerOrder.php");
<?php
}
?>

<?php
if($return_param["card"] == "membercard") { 
?>
post(post_data, "http://<?php echo $_SERVER['SERVER_NAME'];?>/submitMemberCardOrder.php");
<?php
}
?>

<?php
		} else {
?>
window.close();
<?php
		}
?>
</script>
</body>
</html>
<?php
		die();
	}
}

$path = $this->baseurl.'/templates/'.$this->template;
$bootstrap = $this->params->get('bootstrap');
$bootstrap_js = $this->params->get('bootstrap_js');
$column_responsive = $this->params->get('column_responsive');
$website_title = $this->params->get('website_title');
$color_theme_menu = $this->params->get('color_theme_menu');
$color_theme_content = $this->params->get('color_theme_content');
$color_text = $this->params->get('color_text');
$min_height_menu = $this->params->get('min_height_menu');
$shadow_content_box = $this->params->get('shadow_content_box');
$transparency_menu = $this->params->get('transparency_menu');
$transparency_content = $this->params->get('transparency_content');
$width_menu = $this->params->get('width_menu');
$width_content = $this->params->get('width_content');
$width_left = $this->params->get('width_left');
$width_right = $this->params->get('width_right');
$user1_width = $this->params->get('user1_width');
$user3_width = $this->params->get('user3_width');
$user4_width = $this->params->get('user4_width');
$user6_width = $this->params->get('user6_width');
$position_content_box = $this->params->get('position_content_box');
$button_fullscreen = $this->params->get('button_fullscreen');
$color_theme = $this->params->get('color_theme');
$font = $this->params->get('font');
$font_title = $this->params->get('font_title');
$font_content = $this->params->get('font_content');
$text_social_icons = $this->params->get('text_social_icons');
$google1 = $this->params->get('google1');
$responsive = $this->params->get('responsive');
$mobile_menu = $this->params->get('mobile_menu');

$app = JFactory::getApplication();

$mobileMode = $app->getUserState('cmobile.ismobile', false);
$menu = $app->getMenu();
$lang = JFactory::getLanguage();

$current_lang = $lang->getTag();
$current_lang = substr($current_lang, 0, 2);

$session = JFactory::getSession();

if ($menu->getActive() == $menu->getDefault($lang->getTag())) {
$js='<div class="js-copyright" ></div>';
} else {$js='<div class="js-copyright" ></div>' ;}

if ($this->params->get('fontSize') == '') 
{ $fontSize ='0.75em'; } 
else { $fontSize = $this->params->get('fontSize'); }

if( ($this->countModules('google_map')) || ($this->countModules('video')) )
{ $position_content_box = 'full_width' ; $button_fullscreen = '0' ; $transparency_menu = '1'; }


JHtml::_('behavior.framework', true);

if ($bootstrap_js == 'yes') {
JHtml::_('bootstrap.framework');
}

?>

<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->language; ?>" lang="<?php echo $this->language; ?>" dir="<?php echo $this->direction; ?>" >

<head>
<script>
var invalidErrorMsg = "<?php if($current_lang == "en") echo "Please complete the human validation first !! ( It's located before 'PROCEED' button.)"; else if($current_lang == "th") echo "กรุณาทำการยืนยันตัวตนก่อน !! ( กรอกฟอร์มที่อยู่ก่อนปุ่ม 'ส่ง' )"; ?>";
var rootPath = "<?php echo JURI::base();?>";
var doneMsg = "<?php echo ($current_lang == "th" ? "ส่งเรียบร้อย<br />กรุณารอรับอีเมลล์ตอบกลับจากเรา" : "DONE<br />PLEASE WAIT FOR OUR CONTACT.")?>";
var lang = "<?php echo $current_lang;?>";
var dateFormat = "<?php echo ($current_lang == 'en' || $current_lang == '' ? 'd/m/Y' : 'd.m.Y');?>";
var current_price = 0;
var exchangeRate = 1;
</script>
<script src="includes/ThaiPattara_Function.js" type="text/javascript"></script>
<jdoc:include type="head" />

<?php if ($responsive == 'yes') : ?>
<meta name="viewport" content="initial-scale=1" />
<?php endif; ?>

<script type="text/javascript">
	if (typeof jQuery === 'undefined') {
	    document.write(unescape("%3Cscript src='<?php echo $this->baseurl ?>/templates/<?php echo $this->template; ?>/lib/js/jquery-181.js' type='text/javascript'%3E%3C/script%3E"));
    }
</script>
<script type="text/javascript">
	jQuery.noConflict();
</script>

<?php if ($bootstrap == 'yes') : ?>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template; ?>/css/bootstrap.css" media="screen" />
<?php endif; ?>

<!--	font-face	-->
<?php if ( ($font_title != 'Tahoma')  && ($font_title != 'Arial')  && ($font_title != 'Georgia')  && ($font_title != 'Trebuchet ms')  && ($font_title != 'Times new roman')  && ($font_title != 'Verdana')  ) : ?>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/font-<?php echo $font_title ; ?>.css" type="text/css" media="all" />
<?php endif; ?>
<?php if ( ($font != 'Tahoma')  && ($font != 'Arial')  && ($font != 'Georgia')  && ($font != 'Trebuchet ms')  && ($font != 'Times new roman')  && ($font != 'Verdana') && ($font != $font_title) ) : ?>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/font-<?php echo $font ; ?>.css" type="text/css" media="all" />
<?php endif; ?>


<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/system/css/general.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/main.css" type="text/css" media="all" />
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/nav.css" type="text/css" media="all" />
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/template.css" type="text/css" media="all" />
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/lib/js/theme/supersized.shutter.css" type="text/css" />
<?php if ($bootstrap == 'yes') : ?>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template; ?>/css/overwrite-bootstrap.css" type="text/css" media="screen" />
<?php endif; ?>
<?php if ($color_theme_menu == 'black') : ?>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/black-theme.css" type="text/css" />
<?php endif; ?>
<?php if ($color_text == 'white') : ?>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/white-text.css" type="text/css" />
<?php endif; ?>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/theme-<?php echo $color_theme ; ?>.css" type="text/css" media="all" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/dynamic_css.php&#63;font=<?php echo $font ; ?>&amp;font_title=<?php echo $font_title ; ?>&amp;font_content=<?php echo $font_content ; ?>&amp;width_menu=<?php echo $width_menu ; ?>&amp;width_content=<?php echo $width_content ; ?>&amp;width_left=<?php echo $width_left ; ?>&amp;width_right=<?php echo $width_right ; ?>" media="all" />

<?php if( ($mobile_menu == 'yes') && ( strstr($_SERVER['HTTP_USER_AGENT'],'Android') || strstr($_SERVER['HTTP_USER_AGENT'],'iPad') || strstr($_SERVER['HTTP_USER_AGENT'],'webOS') || strstr($_SERVER['HTTP_USER_AGENT'],'iPhone') || strstr($_SERVER['HTTP_USER_AGENT'],'iPod') || strstr($_SERVER['HTTP_USER_AGENT'],'blackberry') || strstr($_SERVER['HTTP_USER_AGENT'],'Windows Phone') || strstr($_SERVER['HTTP_USER_AGENT'],'Palm') || strstr($_SERVER['HTTP_USER_AGENT'],'symbian') )  ) : ?>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/menu_mobile.css" type="text/css" media="all" />
<?php endif ; ?>

<?php if ($responsive == 'yes') : ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/media_queries.css" media="screen" />
<?php else : ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/media_queries_no_responsive.css" media="screen" />
<?php endif; ?>

<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/print.css" type="text/css" media="print" />

<style type="text/css">
@media screen and (max-height: <?php echo $min_height_menu ; ?>px) and (min-width: 980px) {

	#column-menu {
	position:absolute;
	}
	
	.sidebar-footer {
	position : relative;
	}
}
</style>
<!--[if lte IE 9]>
<style type="text/css">
	.gradient {
    filter: none;
    }
</style>
<![endif]-->
<!--[if lte IE 8]>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/ie8.css" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/lib/js/html5.js"></script>
<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/lib/js/css3-mediaqueries.js"></script>
<?php if ($responsive == 'yes') : ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/ie8_responsive.css" media="screen" />
<?php endif; ?>
<![endif]-->

<!--[if lte IE 7]>
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/ie7.css" type="text/css" />
<?php if ($responsive == 'yes') : ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/css/ie7_responsive.css" media="screen" />
<?php endif; ?>
<![endif]-->

<!--	supersized	-->
<?php if( ($this->countModules('supersized')) && (! $this->countModules('google_map')) && (! $this->countModules('video')) ) : ?>

	<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/lib/js/supersized.3.2.1.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/lib/js/theme/supersized.shutter.js"></script>
	<script type="text/javascript">  
		<jdoc:include type="modules" name="supersized" style="joomspirit" />
	</script>
	
	<?php if($button_fullscreen == '1') : ?>
	<script type="text/javascript">
	window.addEvent('domready', function() {
	
		jQuery.noConflict();
<?php
if(strpos($_SERVER['REQUEST_URI'], 'promotion') !== FALSE || strpos($_SERVER['REQUEST_URI'], '%D0%BF%D1%80%D0%BE%D0%BC%D0%BE%D0%B0%D0%BA%D1%86%D0%B8%D1%8F') !== FALSE){
?>
		jQuery('.farewell').remove();
<?php
}
?>
	
		jQuery('#close-button').click(function(){
			
			jQuery('#nextslide').toggleClass('hide_function');
			jQuery('#prevslide').toggleClass('hide_function');
		  
		});
		
		jQuery('#open-button').click(function(){
			
			jQuery('#nextslide').toggleClass('hide_function');
			jQuery('#prevslide').toggleClass('hide_function');
		  
		});	
		
	});
	</script>
	<?php endif; ?>	
	
<?php endif; ?>

<!--	button for fullscreen	-->
<?php if($button_fullscreen == '1') : ?>
<script type="text/javascript">
window.addEvent('domready', function() {

	jQuery.noConflict();

	jQuery('#close-button').click(function(){
		
		jQuery('#column-content').toggle(700);
		jQuery('.website-footer').toggleClass('hide_function');
		jQuery('#close-button').toggle(50);
		jQuery('#thumb-tray').toggleClass('hide_function');
		jQuery('#open-button').toggle(1000);
	  
	});
	
	jQuery('#open-button').click(function(){
		
		jQuery('#column-content').toggle(750);
		jQuery('.website-footer').toggleClass('hide_function');
		jQuery('#close-button').toggle(1300);
		jQuery('#thumb-tray').toggleClass('hide_function');
		jQuery('#open-button').toggle(350);
	  
	});
});
</script>
<?php endif; ?>

<?php if( $this->countModules('video') ) : ?>
<script type="text/javascript">
//<![CDATA[
window.addEvent('domready', function() {

	jQuery('#navigation').click(function () {
	jQuery('#height_video').toggle();
	});	
	
});
//]]>
</script>
<?php endif; ?>


<?php if ($bootstrap_js == 'yes') : ?>
<script src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template; ?>/lib/js/bootstrap.min.js"></script>
<?php endif; ?>	
<script>
jQuery(function(){
	jQuery('#navigation').find('.nav.menu').find('li:first').hide()
	cart_view();
    jQuery(document).find('[tooltip]').tooltip();
	jQuery('[id^=YMapsCredit]').hide();

	jQuery('#card_type').change(function(){
		if(jQuery('#card_type option:first').is(':selected')) 
		{ 
			jQuery('#money_tr').hide(); 
			jQuery('#SPA_PROGRAM').val(''); 
			jQuery('#spa_program_tr').show(); 
		} else { 
			jQuery('#spa_program_tr').hide(); 
			jQuery('#money_amount').val(''); 
			jQuery('#money_tr').show(); 
		}
		jQuery('#price').html('0');
	});
	
	jQuery('#SPA_PROGRAM').change(function(){
		if(jQuery(this).find('option:first').is(":selected"))
			current_price = 0;
		else
		{
			var tmp = jQuery(this).find('option:selected').text().split(' -- ');
			var tmp = tmp[1].split(' ');
			current_price = tmp[0].replace(',', '') * exchangeRate;
		}
		jQuery('#price').html(formatNumber(current_price));
	});
	
	jQuery('#money_amount').keyup(function(){
		if(jQuery('#money_amount').val().trim() == '')
			current_price = 0;
		else
			current_price = jQuery('#money_amount').val() * exchangeRate;
		
		jQuery('#price').html(formatNumber(current_price));
	});
	
	jQuery('#currency_text').change(function(){
		if(jQuery('#currency_text').val() == 'RUB')
			exchangeRate = 1;
		else
			exchangeRate = 0.04;
		
		jQuery('#price').html(formatNumber(current_price * exchangeRate));
	});
	
	jQuery('#fancybox-content').css('border', '0px');
	jQuery('#fancybox-wrap > div:first').remove();
	//jQuery('#fancybox-wrap').css('width', jQuery('#fancybox-wrap').css('width') - 20);
	
	jQuery("#cart_view")
	.dialog({
		autoResize: true,
		autoOpen:false,
		closeOnEscape: false,
		modal:true,
		width: "auto",
		height: "auto",
		draggable: false,
		resizable: false,
		minHeight: '1px',
		show: { effect: "fade", duration: 250 },
		hide: { effect: "fade", duration: 250 },
		buttons: {}
	}).dialog( "widget" )
	.find("div.ui-dialog-titlebar")
	.remove()
	.find('.ui-dialog-titlebar-close')
	.find('span:first')
	.css('left', '0px')
	.css('top', '0px');
<?php
	/*if(!$mobileMode){
		$session_expired = false;
		if(strpos(JURI::current(), 'home') !== FALSE || strpos(JURI::current(), 'главная') !== FALSE || strpos(JURI::current(), '%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F') !== FALSE){
			if($session->get('current_lang')){
				if($session->get('current_lang') != $current_lang) {
					$session_expired = true;
				} else {
					if($session->get('last_popup')){
						$date1 = new DateTime($session->get('last_popup'));
						$date2 = new DateTime("now");
						$interval = $date2->diff($date1);
						if((int)$interval->format('%H') >= 1) $session_expired = true;
					} else {
						$session_expired = true;
					}
				}
			} else {
				$session_expired = true;
			}
		}*/
/*?>
	console.log('<?php echo $session->get('current_lang') . " - " . $current_lang;?>');
	console.log('<?php echo $session->get('last_popup');?>');
	console.log('<?php echo date('Y-m-d H:i:s');?>');
	console.log('<?php if($interval != null) echo (int)$interval->format('%H');?>');
	console.log('SESSION_EXPIRED ? <?php echo ($session_expired ? 'true' : 'false'); ?>');
<?php*/
		//if($session_expired){
	// PRELOAD IMAGES
	$files = scandir("images/promotion/");
	$file_list = array();
	foreach($files as $index => $filename){
		if($index > 1) array_push($file_list, '"' . $filename . '"');
	}
?>	
	var filelist = [<?php echo implode(', ', $file_list);?>];
	jQuery.fn.preload = function() {
		file_count = this.length;
		this.each(function(){
			var image = new Image();
			image.onload = function () {
				file_count = file_count - 1;
			}
			image.onerror = function () {
				file_count = file_count - 1;
			}
			image.src = "../images/promotion/" + this;
		});
		var intervalChecker = setInterval(function(){
			if(file_count == 0){
				jQuery('.promotion_popup').trigger('click');
				clearInterval(intervalChecker);
			}
		}, 1000);
	}
	jQuery(filelist).preload();
<?php
	$session->set('last_popup', date_format(new DateTime("now"), 'Y-m-d H:i:s'));
	$session->set('current_lang', $current_lang);
		//}
	//}
?>
<?php if($mobileMode){ ?>
	if(window.location.href.indexOf('#navigation') > -1) {
		jQuery('.logo').css('z-index', '0');
		jQuery('#translate').css('z-index', '0');
		jQuery('.nav.menu').css('z-index', '99');
	} else {
		jQuery('.logo').css('z-index', '99');
		jQuery('#translate').css('z-index', '99');
		jQuery('.nav.menu').css('z-index', '0');
	}
	jQuery('#YMapsID, .ymaps-glass-pane.ymaps-events-pane, .ymaps-glass-pane.ymaps-events-pane').css('height', '300px');
<?php } ?>
});
</script>
<?php
//if(strpos(JURI::current(), 'contact-us') !== FALSE || strpos(JURI::current(), 'контакты') !== FALSE) {
?>
<script>
var captchaWidget;
var onloadCallback = function() {
	if(jQuery('#captcha').length > 0){
		captchaWidget = grecaptcha.render('captcha', {
			'sitekey' : '6LcoQQITAAAAAEQ9oAXXFPeh8gFfN9B0sgNj4vGU'
		});
	}
}
</script>
<script src='https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit<?php if($current_lang != "") echo "&hl=" . $current_lang?>' async defer></script>
<?php
//}
?>
<link rel="stylesheet" type="text/css" href="includes/jquery.datetimepicker.css"/ >
<script src="includes/jquery.datetimepicker.js" type="text/javascript"></script>
<meta name='yandex-verification' content='6b395d48d1c001e1' />
<meta name="google-site-verification" content="7KMkXhcqkaDYExOs3Pxa7zmiT2dgJqVFeH38tLhzU0o" />

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63756624-1', 'auto');
  ga('send', 'pageview');

</script>

<script type="text/javascript">
  var top_show = 150; // В каком положении полосы прокрутки начинать показ кнопки "Наверх"
  var delay = 500; // Задержка прокрутки
  jQuery(document).ready(function() {
    jQuery(window).scroll(function () { // При прокрутке попадаем в эту функцию
      /* В зависимости от положения полосы прокрукти и значения top_show, скрываем или открываем кнопку "Наверх" */
      if (jQuery(this).scrollTop() > top_show) jQuery('#backtop').fadeIn();
      else jQuery('#backtop').fadeOut();
    });
    jQuery('#backtop').click(function () { // При клике по кнопке "Наверх" попадаем в эту функцию
      /* Плавная прокрутка наверх */
      jQuery('body, html').animate({
        scrollTop: 0
      }, delay);
    });
  });
</script>
<script type="text/javascript" src="/ds-comf/ds-form/js/dsforms.js"></script>

</head>

<body <?php echo ('style="font-size:'.$fontSize.';"');?> class="menu-<?php echo $color_theme_menu ; ?> content-<?php echo $color_theme_content ; ?> <?php if ($color_text == 'white') : ?>white-text<?php endif ; ?> <?php if($this->countModules('home_page')) : ?>home_page<?php endif ; ?>" >
<div id="backtop"></div>
<div data-dspopup-id="callme" id="callme_bt">Заказать звонок</div>

<?php
/*echo "current_url" . JURI::current() . "<BR>";
echo "last popup = " . $session->get('last_popup') . "<BR />";
echo "session_expired = " . ($session_expired == true ? 'true' : 'false') . "<BR />";*/
?>
	<div id="cart_view" style="display: none; padding: 0px;">
	<center>
	<table class="table table-bordered">
	<caption style="background-color: black; vertical-align: middle; text-align: center; padding: 5px;" class="btn-success"><span style="font-weight: bold; text-align: center"><?php if($current_lang == 'ru') { ?>ВАШЕ БРОНИРОВАНИЕ<?php } else { ?>YOUR BOOKING<?php } ?></span><button class="btn btn-mini pull-right" style="" onclick="jQuery('#cart_view').dialog('close');"><i class="icon-remove" style="margin-top: 2px;"></i></button></caption>
	</table>
	<div style="margin-top: -17px; margin-bottom: 1px;">
	<button class="btn btn-mini btn-danger" title="<?php if($current_lang == 'ru') { ?>Отчистить все<?php } else { ?>Clear All Items<?php } ?>" style="margin-left: 1px;" id="clear_cart_btn" onclick="cart_clear(); return false;"><i class="icon-remove icon-white" style="margin-right: 5px; margin-top: 2px;"></i><?php if($current_lang == 'ru') { ?>ОТЧИСТИТЬ<?php } else { ?>CLEAR<?php } ?></button>
	<button class="btn btn-mini btn-success" title="<?php if($current_lang == 'ru') { ?>Отправить бронирование<?php } else { ?>Sumbit Your Booking<?php } ?>" onclick="void(yaCounter30728608.reachGoal('reserve')); void(ga('send', 'pageview', '/virtual/reserv/')); cart_checkout(); return false;"><i class="icon-ok icon-white" style="margin-right: 5px; margin-top: 2px;"></i><?php if($current_lang == 'ru') { ?>БРОНИРОВАТЬ<?php } else { ?>RESERVE<?php } ?></button>
	</div>
	</center>
	</div>

	<div id="column-menu" class="zindex3 clearfix <?php echo $color_theme_menu ; ?><?php echo $transparency_menu ; ?>" >
		<div id="main-column-menu" class="<?php //clearfix ?>"<?php if($mobileMode) {?><?php } ?>>
		
			<div class="logo" style="<?php if(!$mobileMode){ ?>margin-top: -30px;<?php }?>width: 100%; text-align: center;">
			<?php if($this->countModules('logo')) : ?>
				<jdoc:include type="modules" name="logo" style="joomspirit" />
			<?php else : ?>
				<a href="index.php" >
				<span>
					<?php echo $website_title ; ?>
				</span>
				</a>
			<?php endif; ?>
			</div>
			
			<?php if($this->countModules('breadcrumb')) : ?>
			<div id="cart_placeholder" style="display: none; background-color: white; border: 1px solid #CCCCCC; <?php if(!$mobileMode){ ?>margin: -5px 0 15px 0;<?php }?>" class="img-rounded shadow-light">
				<jdoc:include type="modules" name="breadcrumb" style="xhtml" />
			</div>	
			<?php endif; ?>

<?php /*
			<?php if($this->countModules('breadcrumb')) : ?>
				<nav class="breadcrumb">
					<jdoc:include type="modules" name="breadcrumb" style="xhtml" />
				</nav>	
				<?php endif; ?>
*/?>
			
			<?php if($this->countModules('menu')) : ?>
			<nav id="navigation" class="drop-down" role="navigation" onclick="jQuery('.logo').css('z-index', '0'); jQuery('#translate').css('z-index', '0'); jQuery('.nav.menu').css('z-index', '99');">
				<jdoc:include type="modules" name="menu" style="joomspirit" />
			</nav>
			<?php endif; ?>
	
			<?php if ($this->countModules( 'search' )) : ?>
			<div class="search-module visible-desktop" style="margin: 20px 0px 0px 0px; width: 100%; position: relative; left: 0px; z-index: 99" >
				<jdoc:include type="modules" name="search" style="xhtml" />
			</div>	
			<?php endif; ?>
			
			<?php if ($this->countModules( 'translate' )) : ?>
			<div id="translate" style="width: 100%; position: relative; z-index: 9; text-align: center; <?php if($mobileMode === true) {?>margin: 0px; left: 0px; top: 4px; margin-bottom: 2px;<?php } ?>">
				<jdoc:include type="modules" name="translate" style="xhtml" />
			</div>
			<?php endif; ?>
				
		</div>
		
		<div class="sidebar-footer visible-desktop">
			<?php if($this->countModules('address')) : ?>
			<div class="address">
				<jdoc:include type="modules" name="address" style="joomspirit" />
					<div class="li"></div>
			</div>
			<?php endif; ?>
			
		</div>		<!-- end of sidebar footer		-->		
		
		
	</div>	<!-- end of column menu		-->
	

	<?php if($this->countModules('google_map')) : ?>
	<div class="module_google_map scale" >
		<jdoc:include type="modules" name="google_map" style="joomspirit" />
	</div>
	<?php endif; ?>
	
	<?php if($this->countModules('video')) : ?>
	<div class="module_video scale" >
		<jdoc:include type="modules" name="video" style="joomspirit" />
	</div>
	<?php endif; ?>
	

	<?php if( ! $this->countModules('home_page') ) : ?>
	<div id="column-content" style="font-weight: bold;" class="zindex1 <?php if( $position_content_box !='full_width') : ?>shadow-<?php echo $shadow_content_box ; ?><?php endif; ?> <?php if( $position_content_box =='full_width') : ?><?php echo $color_theme_content ; ?><?php echo $transparency_content ; ?><?php endif; ?> <?php if( ($this->countModules('google_map')) || ($this->countModules('video')) ) : ?>no_min_height<?php endif ; ?>">
		<center>
		<div id="main-column-content" class=" zindex1 <?php /*echo $position_content_box ; ?>*/?>" style="text-align: left; position: relative; top: 0px; <?php if($mobileMode){ ?>overflow-x: scroll; overflow-y: hidden; width : 100%;<?php }?>">
			<center>
<?php /*
				<div style="margin-top: 10px;">
				<?php if($current_lang == "en") { ?>
				<span class="text-warning" style="font-weight: bold;">7 Days Open 10.00AM - Midnight.</span><br />
				<span class="text-success" style="font-weight: bold;">Special !! Dec 25 - Jan 15 open everyday from 09.00AM - 02.00AM</span>
				<?php } else { ?>
				<span class="text-warning" style="font-weight: bold;">Мы открыты 7 дней в неделю с 10:00 до 24:00.</span><br />
				<span class="text-success" style="font-weight: bold;">Акция! С 25 декабря по 15 января мы открыты ежедневно с 9:00 утра до 2:00 ночи</span>
				<?php } ?>
				</div>
*/?>
				<a target="_blank" href="http://www.thai-center.ru/<?php echo $current_lang; ?>/">
					<img class="image" style="margin-bottom: 0;" title="Thai Pattara Ресторан" alt="Thai Pattara Ресторан" src="/images/thai pattara restaurant.jpg">
				</a>
			</center>
			<!--  USER 1, 2, 3 -->
			<?php if($this->countModules('user1') || $this->countModules('user2') || $this->countModules('user3')) : ?>
			<aside class="users_top clearfix" style="padding-bottom: 0;">
				
				<!--	SOCIAL LINKS	-->
			
				<?php if( ($google1 == 'yes') || ($this->params->get('twitter') != '') || ($this->params->get('blogger') != '') || ($this->params->get('delicious') != '') || ($this->params->get('flickr') != '') || ($this->params->get('facebook') != '') || ($this->params->get('digg') != '') || ($this->params->get('rss') != '') || ($this->params->get('linkedin') != '') || ($this->params->get('myspace') != '') || ($this->params->get('youtube') != '') || ($this->params->get('vimeo') != '') || ($this->params->get('picasa') != '') || ($this->params->get('stumbleupon') != '') || ($this->params->get('technorati') != '') || ($this->params->get('tumblr') != '') || ($this->params->get('yahoo') != '') ) : ?>
				<div class="social-links">
					<ul>
						
						<?php if ($text_social_icons != '') : ?>
						<li class="text_social_icons"><span><?php echo $text_social_icons ; ?></span></li>
						<?php endif; ?>
						
						<?php if ($google1 == 'yes') : ?>
						<li class="google">
						<div class="g-plusone" data-size="small" data-count="false" ></div>
						</li>
						<?php endif; ?>
						
						<?php if ($this->params->get('twitter') != '') : ?>
						<li><a target="_blank" class="twitter" title="Twitter" href="<?php echo $this->params->get('twitter') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/twitter-bird3.png" alt="" /></a></li>
						<?php endif; ?>		
						<?php if ($this->params->get('blogger') != '') : ?>
						<li><a target="_blank" class="blogger" title="Blogger" href="<?php echo $this->params->get('blogger') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/blogger.png" alt="" /></a></li>
						<?php endif; ?>
				
						<?php if ($this->params->get('delicious') != '') : ?>
						<li><a target="_blank" class="delicious" title="Delicious" href="<?php echo $this->params->get('delicious') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/delicious.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('facebook') != '') : ?>
						<li><a target="_blank" class="facebook" title="Facebook" href="<?php echo $this->params->get('facebook') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/facebook-logo.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('rss') != '') : ?>
						<li><a target="_blank" class="rss" title="RSS" href="<?php echo $this->params->get('rss') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/rss-badge.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('linkedin') != '') : ?>
						<li><a target="_blank" class="linkedin" title="Linkedin" href="<?php echo $this->params->get('linkedin') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/linkedin-logo.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('myspace') != '') : ?>
						<li><a target="_blank" class="myspace" title="Myspace" href="<?php echo $this->params->get('myspace') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/myspace-logo.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('yahoo') != '') : ?>
						<li><a target="_blank" class="yahoo" title="Yahoo" href="<?php echo $this->params->get('yahoo') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/yahoo.png" alt="" /></a></li>
						<?php endif; ?>
				
						<?php if ($this->params->get('flickr') != '') : ?>
						<li><a target="_blank" class="flickr" title="Flickr" href="<?php echo $this->params->get('flickr') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/flickr.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('youtube') != '') : ?>
						<li><a target="_blank" class="youtube" title="Youtube" href="<?php echo $this->params->get('youtube') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/you-tube1.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('vimeo') != '') : ?>
						<li><a target="_blank" class="vimeo" title="Vimeo" href="<?php echo $this->params->get('vimeo') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/vimeo.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('digg') != '') : ?>
						<li><a target="_blank" class="digg" title="Digg" href="<?php echo $this->params->get('digg') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/digg.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('picasa') != '') : ?>
						<li><a target="_blank" class="picasa" title="Picasa" href="<?php echo $this->params->get('picasa') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/picasa.png" alt="" /></a></li>
						<?php endif; ?>	
						<?php if ($this->params->get('stumbleupon') != '') : ?>
						<li><a target="_blank" class="stumbleupon" title="Stumbleupon" href="<?php echo $this->params->get('stumbleupon') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/stumbleupon.png" alt="" /></a></li>
						<?php endif; ?>	
						<?php if ($this->params->get('technorati') != '') : ?>
						<li><a target="_blank" class="technorati" title="Technorati" href="<?php echo $this->params->get('technorati') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/technorati-logo.png" alt="" /></a></li>
						<?php endif; ?>	
						<?php if ($this->params->get('tumblr') != '') : ?>
						<li><a target="_blank" class="tumblr" title="Tumblr" href="<?php echo $this->params->get('tumblr') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/tumblr.png" alt="" /></a></li>
						<?php endif; ?>
						
						
					</ul>
				</div> 			<!-- 	end of Website icons 		-->
				<?php endif; ?>	
														
				<?php if($this->countModules('user1')) : ?>
				<div class="user1" <?php echo ('style="width:'.$user1_width.'%;"');?>>
					<jdoc:include type="modules" name="user1" style="joomspirit" />
				</div>
				<?php endif; ?>
									
				<?php if($this->countModules('user3')) : ?>
				<div class="user3" <?php echo ('style="width:'.$user3_width.'%;"');?>>
					<jdoc:include type="modules" name="user3" style="joomspirit" />
				</div>
				<?php endif; ?>
			
				<?php if($this->countModules('user2')) : ?>
				<div class="user2">
					<jdoc:include type="modules" name="user2" style="joomspirit" />
				</div>
				<?php endif; ?>
									
			</aside>
			<?php endif; ?>  <!--	END OF USERS TOP	-->
		
			<div class="all-content zindex1 <?php if( $position_content_box !='full_width') : ?><?php echo $color_theme_content ; ?><?php echo $transparency_content ; ?><?php endif; ?>" style="<?php if(!$mobileMode) { ?> padding: 20px;<?php } ?>">
				
				<?php if ($button_fullscreen == '1') : ?>
				<div id="close-button" style="position: relative; float: right; top: -10px; left: 10px"></div>
				<?php endif; ?>
				
				<?php if($this->countModules('top')) : ?>
				<div class="top-module-position clearfix" >
					<jdoc:include type="modules" name="top" style="joomspirit" />
				</div>
				<?php endif; ?>
	
				<?php if($this->countModules('left')) : ?>
				<aside class="left_column arrow_red <?php if ( $column_responsive == 'yes' && $responsive == 'yes' ) : ?>visible-desktop<?php endif; ?>" >
					<div>
					<jdoc:include type="modules" name="left" style="joomspirit" />
					</div>
				</aside>
				<?php endif; ?>
				
				<?php if($this->countModules('right')) : ?>
				<aside class="right-module-position arrow_red <?php if ( $column_responsive == 'yes' && $responsive == 'yes' ) : ?>visible-desktop<?php endif; ?>" >
					<div>
					<jdoc:include type="modules" name="right" style="joomspirit" />
					</div>
				</aside>
				<?php endif; ?>

				
				<div class="content">
					
					<div class="main_component" >
					
						<!--  MAIN COMPONENT -->
						<jdoc:include type="message" />
						<jdoc:include type="component" />
							
					</div>
						
					
					<!--  USER 4, 5, 6 -->
					<?php if($this->countModules('user4') || $this->countModules('user5') || $this->countModules('user6')) : ?>
					<aside class="users_bottom clearfix">
																
						<?php if($this->countModules('user4')) : ?>
						<div class="user4" <?php echo ('style="width:'.$user4_width.'%;"');?>>
							<jdoc:include type="modules" name="user4" style="joomspirit" />
						</div>
						<?php endif; ?>
											
						<?php if($this->countModules('user6')) : ?>
						<div class="user6" <?php echo ('style="width:'.$user6_width.'%;"');?>>
							<jdoc:include type="modules" name="user6" style="joomspirit" />
						</div>
						<?php endif; ?>
					
						<?php if($this->countModules('user5')) : ?>
						<div class="user5">
							<jdoc:include type="modules" name="user5" style="joomspirit" />
						</div>
						<?php endif; ?>
											
					</aside>
					<?php endif; ?>  <!--	END OF USERS BOTTOM	-->
					
				</div>	<!-- end of content	-->

				<div class="clr"></div>

				<?php if( ($this->countModules('left')) && ($column_responsive == 'yes') && ($responsive == 'yes') ) : ?> 				<!-- Left and right column are duplicate to modify the order on mobiles devices 	-->
				<aside class="left_column hidden-desktop" >
					<div>
					<jdoc:include type="modules" name="left" style="joomspirit" />
					</div>
				</aside>
				<?php endif; ?>
				
				<?php if( ($this->countModules('right')) && ($column_responsive == 'yes') && ($responsive == 'yes') ) : ?>
				<aside class="right-module-position hidden-desktop" >
					<div>
					<jdoc:include type="modules" name="right" style="joomspirit" />
					</div>
				</aside>
				<?php endif; ?>
				
				
				<?php if($this->countModules('bottom')) : ?>
				<div class="bottom-module-position" >
					<jdoc:include type="modules" name="bottom" style="joomspirit" />
				</div>
				<?php endif; ?>
					
			</div>
			
		</div>
		</center>		<!-- 	end of Main column content 			-->
		
	</div>			<!-- end of Column-content	 -->
	<?php endif; ?>		
		

		<?php if( $this->countModules('home_page') ) : ?>
			<div class="empty-space-home-page"></div>
		<?php endif; ?>
		
		<!--				Footer only on Mobiles 		-->
		<div class="website-footer clearfix zindex2 hidden-desktop <?php echo $color_theme_menu ; ?><?php echo $transparency_menu ; ?> <?php if( $this->countModules('home_page') ) : ?>footer-home-page<?php endif; ?>">
		
			<?php if ($this->countModules( 'search' )) : ?>
			<div class="search-module" >
				<jdoc:include type="modules" name="search" style="xhtml" />
			</div>	
			<?php endif; ?>
					
			<!--	SOCIAL LINKS	-->
			<?php if( ($google1 == 'yes') || ($this->params->get('twitter') != '') || ($this->params->get('blogger') != '') || ($this->params->get('delicious') != '') || ($this->params->get('flickr') != '') || ($this->params->get('facebook') != '') || ($this->params->get('digg') != '') || ($this->params->get('rss') != '') || ($this->params->get('linkedin') != '') || ($this->params->get('myspace') != '') || ($this->params->get('youtube') != '') || ($this->params->get('vimeo') != '') || ($this->params->get('picasa') != '') || ($this->params->get('stumbleupon') != '') || ($this->params->get('technorati') != '') || ($this->params->get('tumblr') != '') || ($this->params->get('yahoo') != '') ) : ?>
			<div class="social-links <?php if ($this->countModules( 'search' )) : ?>with-search<?php endif ; ?>">
	
					<ul>
						
						<?php if ($text_social_icons != '') : ?>
						<li class="text_social_icons"><span><?php echo $text_social_icons ; ?></span></li>
						<?php endif; ?>
						
						<?php if ($google1 == 'yes') : ?>
						<li class="google">
						<div class="g-plusone" data-size="small" data-count="false" ></div>
						</li>
						<?php endif; ?>
						
						<?php if ($this->params->get('twitter') != '') : ?>
						<li><a target="_blank" class="twitter" title="Twitter" href="<?php echo $this->params->get('twitter') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/twitter-bird3.png" alt="" /></a></li>
						<?php endif; ?>		
						<?php if ($this->params->get('blogger') != '') : ?>
						<li><a target="_blank" class="blogger" title="Blogger" href="<?php echo $this->params->get('blogger') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/blogger.png" alt="" /></a></li>
						<?php endif; ?>
				
						<?php if ($this->params->get('delicious') != '') : ?>
						<li><a target="_blank" class="delicious" title="Delicious" href="<?php echo $this->params->get('delicious') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/delicious.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('facebook') != '') : ?>
						<li><a target="_blank" class="facebook" title="Facebook" href="<?php echo $this->params->get('facebook') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/facebook-logo.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('rss') != '') : ?>
						<li><a target="_blank" class="rss" title="RSS" href="<?php echo $this->params->get('rss') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/rss-badge.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('linkedin') != '') : ?>
						<li><a target="_blank" class="linkedin" title="Linkedin" href="<?php echo $this->params->get('linkedin') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/linkedin-logo.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('myspace') != '') : ?>
						<li><a target="_blank" class="myspace" title="Myspace" href="<?php echo $this->params->get('myspace') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/myspace-logo.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('yahoo') != '') : ?>
						<li><a target="_blank" class="yahoo" title="Yahoo" href="<?php echo $this->params->get('yahoo') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/yahoo.png" alt="" /></a></li>
						<?php endif; ?>
				
						<?php if ($this->params->get('flickr') != '') : ?>
						<li><a target="_blank" class="flickr" title="Flickr" href="<?php echo $this->params->get('flickr') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/flickr.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('youtube') != '') : ?>
						<li><a target="_blank" class="youtube" title="Youtube" href="<?php echo $this->params->get('youtube') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/you-tube1.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('vimeo') != '') : ?>
						<li><a target="_blank" class="vimeo" title="Vimeo" href="<?php echo $this->params->get('vimeo') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/vimeo.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('digg') != '') : ?>
						<li><a target="_blank" class="digg" title="Digg" href="<?php echo $this->params->get('digg') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/digg.png" alt="" /></a></li>
						<?php endif; ?>
						<?php if ($this->params->get('picasa') != '') : ?>
						<li><a target="_blank" class="picasa" title="Picasa" href="<?php echo $this->params->get('picasa') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/picasa.png" alt="" /></a></li>
						<?php endif; ?>	
						<?php if ($this->params->get('stumbleupon') != '') : ?>
						<li><a target="_blank" class="stumbleupon" title="Stumbleupon" href="<?php echo $this->params->get('stumbleupon') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/stumbleupon.png" alt="" /></a></li>
						<?php endif; ?>	
						<?php if ($this->params->get('technorati') != '') : ?>
						<li><a target="_blank" class="technorati" title="Technorati" href="<?php echo $this->params->get('technorati') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/technorati-logo.png" alt="" /></a></li>
						<?php endif; ?>	
						<?php if ($this->params->get('tumblr') != '') : ?>
						<li><a target="_blank" class="tumblr" title="Tumblr" href="<?php echo $this->params->get('tumblr') ?>"><img src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/images/social-icons<?php if ( ($color_theme_menu == 'black') ) : ?>-blacktheme<?php endif; ?>/tumblr.png" alt="" /></a></li>
						<?php endif; ?>
						
						
					</ul>
			</div> 			<!-- 	end of Website icons 		-->
			<?php endif; ?>			
			
			<?php if($this->countModules('address')) : ?>
			<div class="address">
				<jdoc:include type="modules" name="address" style="joomspirit" />
					<div class="li"></div>
			</div>
			<?php endif; ?>
		
		</div> 	<!--		end of Footer 		-->		

	<!-- 	Supersized	Arrow Navigation		-->
	<a id="prevslide" class="load-item hide_function" ></a>
	<a id="nextslide" class="load-item hide_function" ></a>
	
			
	<?php if ($button_fullscreen == '1') : ?>
	<div id="open-button" style="display:none;"></div>
	<?php endif; ?>
	

	<!--	supersize	Thumbnail Navigation  -->
	<?php if( ($this->countModules('supersized'))  && (! $this->countModules('google_map'))  && (! $this->countModules('video')) ) : ?>
	
		<div id="thumb-tray" class="load-item hide_function hidden-phone">
			<div id="thumb-back"></div>
			<div id="thumb-forward"></div>
		</div>
		
	<?php endif; ?>
	
	<?php echo $js; ?>
	
	<!--	to prevent of problem of readibility if position Bottom for content box and small screen		-->
	<?php if( $position_content_box=='bottom') : ?>
	<script type="text/javascript">
		function PositionContent(){
		  var height_window = document.documentElement.clientHeight;
		  var height_content = document.getElementById('main-column-content').clientHeight;
		  if ( height_window < (height_content + 30) ) { document.getElementById("main-column-content").className = 'zindex1 top'; }
		}
		
		// Une fonction de compatibilité pour gérer les évènements
		function addEvent(element, type, listener){
		  if(element.addEventListener){
			element.addEventListener(type, listener, false);
		  }else if(element.attachEvent){
			element.attachEvent("on"+type, listener);
		  }
		}
		
		addEvent(window, "load", PositionContent);
		addEvent(window, "resize", PositionContent);		
	</script>
	<?php endif; ?>

	<?php if ($google1 == 'yes') : ?>
	<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
	<?php endif; ?>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter30728608 = new Ya.Metrika({id:30728608,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/30728608" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<div id="callme" class="ds-form"></div>
<div rel="33333"></div>
</body>
</html>